---
- hosts: all
  become: yes

  roles:
    - Stouts.openvpn
  #vars_files:
  #  - vars/user.yml
  vars:
    openvpn_clients:
      - test1
      - test2
    openvpn_clients_revoke:
      - test3 
  tasks:
    - name: Send e-mail to a bunch of users, attaching files
      mail:
        host: aspmx.l.google.com
        port: 25
        #secure: never
        #username: user@example.com
        #password: 123456
        from: admin_ansible_test@example.com
        subject: openvpn config
        to: test119@example.com
        body: Hello , this is your openVPN configuration file. I hope you like it ;-)
        attach: /etc/openvpn/keys/test1.zip
        charset: us-ascii

